@startuml GameSequence
'https://plantuml.com/sequence-diagram

skinparam sequenceMessageAlign center

Connection -> Validator : Sends Raw Data

Validator -> Board

Board -> UI : Call UI to Update { Game, Lose, Victory, Withdrawal }

UI -> Board : User Input

alt#Gold #LightBlue Valid Response
    Validator -> Connection : Encapsulate User input and sends raw to Connection
else User Invalid Response
    Board -> UI : Please Repeat
end

alt User Has Won
    Board -> UI : Show Win Image, wait for 30 seconds and close game
else User Has Lost
    Board -> UI : Show Lost Image, wait for 30 seconds and close game
end

@enduml