@startuml
'https://plantuml.com/state-diagram

scale 350 width

[*] -> NOT_STARTED

NOT_STARTED --> IDLE : Received Status != 4 (Not start)

NOT_STARTED -> MY_TURN : Received Status == 4

IDLE --> MY_TURN : Opponent has played

MY_TURN -> CHOICE_ONE : Has selected the first piece

CHOICE_ONE --> CHOICE_TWO : Has selected the second piece

CHOICE_TWO --> IDLE : Sent the game command to opponent


IDLE --> WON : The opponent gave Up
IDLE --> LOST : Has no more moves

MY_TURN --> WON : The opponent has no more moves
MY_TURN --> LOST : Gave Up

@enduml