@startuml
'https://plantuml.com/state-diagram

scale 350 width

[*] -> Idle

Idle --> GameState : Choose First position

state GameState {
    [*] --> GameCommand : Chose the second Position

    GameCommand --> Idle
}

Idle --> ChatState : Ask for Message
state ChatState {
    [*] -> MessageCommand : Write Message

    MessageCommand --> Idle
}

Idle --> OptionState : Ask for Option
state OptionState {
    [*] -> OptionCommand : Choose Option

    OptionCommand --> Idle
}


@enduml